spring:
  application:
    name: spring-poi
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 9099

#线程池配置参数
task:
  pool:
    corePoolSize: 4 #设置核心线程数
    maxPoolSize: 8  #设置最大线程数
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 50 #设置队列容量



